url: "http://admin-api-dev.ap-northeast-2.elasticbeanstalk.com/swagger.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
